[package]
name = "advent_of_code2021"
version = "0.1.0"
authors = ["Fredrik Jansson <frjansso@cisco.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
derive-try-from-primitive = "1.0.0"
lazy_static = "1"
nom = {version = "7", features = []}
nom-regex = "0.2"
regex = "1"
pathfinding = "4"
